//  Copyright © 2019 Paul Langemeijer. All rights reserved.
#include "Protocol_RC5.h"

Protocol_RC5::Protocol_RC5() : Protocol(),
    m_lastTimeCommand(0)
{
    addCodeForCommand(VolumeUp,     0x1010);
    addCodeForCommand(VolumeDown,   0x1011);
    addCodeForCommand(ChannelUp,    0x1020);
    addCodeForCommand(ChannelDown,  0x1021);
    addCodeForCommand(ChannelUp2,   0x1039);    // CD/DVD channel up
    addCodeForCommand(ChannelDown2, 0x1038);    // CD/DVD channel down
    addCodeForCommand(Channel1,     0x1001);
    addCodeForCommand(Channel2,     0x1002);
    addCodeForCommand(Channel3,     0x1003);
    addCodeForCommand(Channel4,     0x1004);
    addCodeForCommand(Channel5,     0x1005);
    addCodeForCommand(Channel6,     0x1006);
    addCodeForCommand(Channel7,     0x1007);
    addCodeForCommand(Channel8,     0x1008);
    addCodeForCommand(TV_OnOff,     0x100C);
}

Protocol::Command Protocol_RC5::getCommand(uint32_t code)
{
    Command command = NoCommand;

    code &= 0xf7ff; //  toggle bit to let you know whether a code was generated by holding down the button or whether this is an independent keypress

    unsigned long debounceTime = 200;       // channel select needs longer debounce time
    if (code == 0x1010 || code == 0x1011)   // VolumeUp or VolumeDown needs short debounce time
        debounceTime = 100; // short

    if (millis() - m_lastTimeCommand > debounceTime)
    {
        command = Protocol::getCommand(code);
        m_lastTimeCommand = millis();
    } 

    return command;
}

