#!/bin/bash -v

# precondition: 'setcd' and 'abcde' have been installed

sudo mkdir /opt/cdcontrol
sudo cp cdcontrol.py /opt/cdcontrol/.
sudo cp startcd.py /opt/cdcontrol/.
sudo cp -r LMSTools /opt/cdcontrol/.
sudo cp cdcontrol.service /etc/systemd/system/.
sudo systemctl enable cdcontrol
sudo systemctl start cdcontrol
